[phases.setup]
nixPkgs = [
  "gcc",
  "postgresql_15.dev",  # Use PostgreSQL 15 instead of 16
  "python39"
]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT"